name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get semantic version
        id: semver
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - uses: actions/checkout@v3
        with:
          ref: v$

      - uses: release-drafter/release-drafter@v5
        id: target_release_notes
        with:
          tag: $
          name: $
          version: $
        env:
          GITHUB_TOKEN: $

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: $
          release-notes: $

      - name: Commit updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: Update changelog'
          file_pattern: CHANGELOG.md
          branch: main

      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.7.12'
      - name: Install dependencies
        run: flutter pub get

      - name: Update version
        run: dart run bull pub_version --version=$

      - name: Commit updated pubspec
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Update version for release'
          file_pattern: pubspec.yaml
          branch: main

      - name: Update Git tag
        run: |
          git tag $ -f
          git push origin $ -f

      - uses: release-drafter/release-drafter@v5
        with:
          tag: $
          name: $
          version: $
          publish: true
        env:
          GITHUB_TOKEN: $

      - name: Publish
        run: flutter pub publish --force